# Generated by Django 3.2.25 on 2024-06-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20240617_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='receive_newsletter',
        ),
    ]
