# Generated by Django 3.2.25 on 2024-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='has_sizes',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sizes',
            field=models.ManyToManyField(to='inventory.Size'),
        ),
    ]
