# Generated by Django 3.2.25 on 2024-05-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20240529_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchise',
            options={'verbose_name_plural': 'Franchises'},
        ),
    ]
