# Generated by Django 3.2.25 on 2024-06-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_franchise_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('SS', 'Small Sale'), ('MS', 'Medium Sale'), ('LS', 'Large Sale')], max_length=2, unique=True),
        ),
    ]
