# Generated by Django 3.2.25 on 2024-06-16 14:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20240613_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='CompositeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.CharField(max_length=20)),
                ('composite_image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_images', to='inventory.inventoryitem')),
            ],
        ),
    ]
