# Generated by Django 3.2.25 on 2024-06-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20240616_1402'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompositeImage',
        ),
    ]
