# Generated by Django 3.2.25 on 2024-06-11 21:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_original_bag_order_original_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default=3, max_length=2),
            preserve_default=False,
        ),
    ]
